import { useState } from 'react'
import { api, setToken } from '../api'
import { useDarkMode } from '../hooks/useDarkMode'
import { useToast } from '../hooks/useToast'
import Icon from './Icon'
import ThemeToggle from './ThemeToggle'

const FEATURES = [
  { icon: 'sparkles', text: '12+ content types generated by AI' },
  { icon: 'pencil', text: 'Refine & rewrite with one click' },
  { icon: 'file', text: 'Export polished PDF & DOCX resumes' },
  { icon: 'chat', text: 'Career assistant chat built in' },
]

const EMAIL_RE = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/

const EMPTY_FORM = { fullName: '', email: '', password: '', confirmPassword: '', otp: '' }

export default function Auth({ onLogin }) {
  const [mode, setMode] = useState('login')
  const [form, setForm] = useState(EMPTY_FORM)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [debugOtp, setDebugOtp] = useState('')
  const toast = useToast()
  const { dark, toggle } = useDarkMode()

  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }))

  function switchMode(next) {
    setMode(next)
    setError('')
    setNotice('')
    setDebugOtp('')
  }

  function validate() {
    const email = form.email.trim()
    if (!email) return 'Email is required.'
    if (!EMAIL_RE.test(email)) return 'Please enter a valid email address.'
    
    if (mode === 'forgot') return ''

    if (mode === 'reset') {
      if (!form.otp.trim()) return 'Verification code is required.'
    }

    if (mode === 'login') {
      if (!form.password) return 'Password is required.'
      return ''
    }
    
    if (mode === 'register' && form.fullName.trim().length < 2) return 'Full name must be at least 2 characters.'
    
    if (mode === 'register' || mode === 'reset') {
      if (form.password.length < 8) return 'Password must be at least 8 characters.'
      if (!/[a-zA-Z]/.test(form.password)) return 'Password must contain at least one letter.'
      if (!/[0-9]/.test(form.password)) return 'Password must contain at least one number.'
      if (form.confirmPassword !== form.password) return 'Passwords do not match.'
    }
    return ''
  }

  async function submit(e) {
    e.preventDefault()
    const validationError = validate()
    if (validationError) {
      setError(validationError)
      return
    }
    setError('')
    setNotice('')
    setLoading(true)
    try {
      if (mode === 'login') {
        const data = await api.login({
          email: form.email.trim().toLowerCase(),
          password: form.password,
        })
        setToken(data.token)
        onLogin(data.user)
      } else if (mode === 'register') {
        await api.register({
          fullName: form.fullName.trim(),
          email: form.email.trim().toLowerCase(),
          password: form.password,
        })
        toast('Account created. Please log in with your new credentials.', 'success')
        setForm((f) => ({ ...f, password: '', confirmPassword: '' }))
        setNotice('Account created successfully. Please log in with your new credentials.')
        setMode('login')
      } else if (mode === 'forgot') {
        const data = await api.forgotPassword({ email: form.email.trim().toLowerCase() })
        if (data.debugOtp) setDebugOtp(data.debugOtp)
        setNotice('A password reset code has been sent to your email.')
        setMode('reset')
      } else if (mode === 'reset') {
        await api.resetPassword({
          email: form.email.trim().toLowerCase(),
          otp: form.otp.trim(),
          password: form.password,
        })
        toast('Password reset successfully. Please log in.', 'success')
        setForm((f) => ({ ...f, password: '', confirmPassword: '', otp: '' }))
        setNotice('Password reset successfully. Please log in with your new password.')
        setMode('login')
      }
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="auth-wrap">
      <div className="auth-blob b1" aria-hidden="true" />
      <div className="auth-blob b2" aria-hidden="true" />
      <div className="auth-blob b3" aria-hidden="true" />

      <div style={{ position: 'absolute', top: 20, right: 20, zIndex: 2 }}>
        <ThemeToggle dark={dark} onToggle={toggle} />
      </div>

      <div className="auth-card">
        <div className="auth-logo">
          <span className="logo">
            <Icon name="brain" size={22} />
          </span>
          <h1 className="grad-text">AI Resume Builder</h1>
        </div>
        <p className="auth-sub">Generate professional resume content in seconds.</p>

        <div className="auth-toggle" role="tablist" aria-label="Authentication mode">
          <button
            className={mode === 'login' || mode === 'forgot' || mode === 'reset' ? 'active' : ''}
            onClick={() => switchMode('login')}
            role="tab"
            aria-selected={mode === 'login' || mode === 'forgot' || mode === 'reset'}
            type="button"
          >
            Login
          </button>
          <button
            className={mode === 'register' ? 'active' : ''}
            onClick={() => switchMode('register')}
            role="tab"
            aria-selected={mode === 'register'}
            type="button"
          >
            Register
          </button>
        </div>

        <form onSubmit={submit} className="auth-form" noValidate>
          {mode === 'register' && (
            <>
              <label htmlFor="rb-fullname">Full Name</label>
              <input
                id="rb-fullname"
                value={form.fullName}
                onChange={set('fullName')}
                placeholder="John Doe"
                autoComplete="name"
                required
              />
            </>
          )}
          
          <label htmlFor="rb-email">Email</label>
          <input
            id="rb-email"
            type="email"
            value={form.email}
            onChange={set('email')}
            placeholder="you@example.com"
            autoComplete="email"
            required
            disabled={mode === 'reset'}
          />

          {mode === 'reset' && (
            <>
              <label htmlFor="rb-otp">Verification Code</label>
              <input
                id="rb-otp"
                type="text"
                value={form.otp}
                onChange={set('otp')}
                placeholder="Enter 6-digit code"
                autoComplete="one-time-code"
                required
              />
            </>
          )}

          {mode !== 'forgot' && (
            <>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 12 }}>
                <label htmlFor="rb-password" style={{ marginTop: 0 }}>
                  {mode === 'reset' ? 'New Password' : 'Password'}
                </label>
                {mode === 'login' && (
                  <button
                    type="button"
                    onClick={() => switchMode('forgot')}
                    style={{ background: 'none', border: 'none', color: 'var(--primary)', fontSize: 13, cursor: 'pointer', padding: 0 }}
                  >
                    Forgot password?
                  </button>
                )}
              </div>
              <div className="password-wrap">
                <input
                  id="rb-password"
                  type={showPassword ? 'text' : 'password'}
                  value={form.password}
                  onChange={set('password')}
                  placeholder={mode === 'register' || mode === 'reset' ? 'At least 8 characters with letters and numbers' : 'Password'}
                  required
                  autoComplete={mode === 'login' ? 'current-password' : 'new-password'}
                />
                <button
                  type="button"
                  className="password-toggle"
                  onClick={() => setShowPassword((s) => !s)}
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                  title={showPassword ? 'Hide password' : 'Show password'}
                >
                  <Icon name={showPassword ? 'eyeOff' : 'eye'} size={16} />
                </button>
              </div>
            </>
          )}

          {(mode === 'register' || mode === 'reset') && (
            <>
              <label htmlFor="rb-confirm">Confirm Password</label>
              <input
                id="rb-confirm"
                type={showPassword ? 'text' : 'password'}
                value={form.confirmPassword}
                onChange={set('confirmPassword')}
                placeholder="Re-enter your password"
                autoComplete="new-password"
                required
              />
            </>
          )}

          {notice && (
            <p className="success" role="status">
              {notice}
            </p>
          )}
          {error && (
            <p className="error" role="alert">
              {error}
            </p>
          )}
          
          {debugOtp && mode === 'reset' && (
            <div style={{ marginTop: 14, padding: 12, borderRadius: 8, background: 'var(--info-bg)', color: 'var(--info)', fontSize: 13, border: '1px solid var(--info)' }}>
              <strong>Debug:</strong> OTP is <code>{debugOtp}</code>
            </div>
          )}

          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? (
              <>
                <span className="spinner" aria-hidden="true" /> Please wait…
              </>
            ) : mode === 'login' ? (
              <>
                <Icon name="send" size={16} /> Login
              </>
            ) : mode === 'forgot' ? (
              <>
                <Icon name="send" size={16} /> Send Reset Link
              </>
            ) : mode === 'reset' ? (
              <>
                <Icon name="check" size={16} /> Reset Password
              </>
            ) : (
              <>
                <Icon name="user" size={16} /> Create Account
              </>
            )}
          </button>
          
          {(mode === 'forgot' || mode === 'reset') && (
            <button
              type="button"
              className="btn btn-ghost"
              onClick={() => switchMode('login')}
              style={{ marginTop: 8 }}
            >
              Back to Login
            </button>
          )}
        </form>

        <div className="auth-features">
          {FEATURES.map((f) => (
            <div key={f.text} className="auth-feature">
              <Icon name={f.icon} size={16} />
              {f.text}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
