export const OUTPUT_TYPES = [
  'professionalHrSummary',
  'resumeSummary',
  'aboutMe',
  'professionalBio',
  'selfIntroduction',
  'interviewIntroduction',
  'linkedinSummary',
  'atsResumeParagraph',
  'coverLetter',
  'emailIntroduction',
  'skillDescription',
  'careerObjective',
]

export const OUTPUT_LABELS = {
  professionalHrSummary: 'Professional HR Summary',
  resumeSummary: 'Resume Summary',
  aboutMe: 'About Me',
  professionalBio: 'Professional Bio',
  selfIntroduction: 'Self Introduction',
  interviewIntroduction: 'Interview Introduction',
  linkedinSummary: 'LinkedIn Summary',
  atsResumeParagraph: 'ATS Resume Paragraph',
  coverLetter: 'Cover Letter',
  emailIntroduction: 'Email Introduction',
  skillDescription: 'Skill Description',
  careerObjective: 'Career Objective',
}

export const FIELDS = [
  { key: 'fullName', label: 'Full Name', icon: '👤', group: 'Details' },
  { key: 'username', label: 'Professional Username', icon: '🏷️', group: 'Details' },
  { key: 'email', label: 'Email', icon: '✉️', group: 'Details' },
  { key: 'phone', label: 'Phone', icon: '📞', group: 'Details' },
  { key: 'jobRole', label: 'Job Title / Role', icon: '💼', group: 'Details' },
  { key: 'company', label: 'Current Company', icon: '🏢', group: 'Details' },
  { key: 'skills', label: 'Skills (comma separated)', icon: '🛠️', group: 'Professional' },
  { key: 'experience', label: 'Experience', icon: '📈', group: 'Professional' },
  { key: 'education', label: 'Education', icon: '🎓', group: 'Professional' },
  { key: 'projects', label: 'Projects', icon: '🚀', group: 'Professional' },
  { key: 'github', label: 'GitHub', icon: '🔗', group: 'Professional' },
  { key: 'linkedin', label: 'LinkedIn', icon: '🔗', group: 'Professional' },
  { key: 'portfolio', label: 'Portfolio', icon: '🌐', group: 'Professional' },
  { key: 'careerObjective', label: 'Career Objective', icon: '🎯', group: 'Objective' },
  { key: 'additionalInfo', label: 'Additional Info', icon: '📝', group: 'Objective' },
]

export const LEVELS = ['beginner', 'mid', 'senior']

export const EMPTY_PROFILE = {
  fullName: '',
  username: '',
  email: '',
  phone: '',
  skills: '',
  company: '',
  jobRole: '',
  experience: '',
  education: '',
  projects: '',
  github: '',
  linkedin: '',
  portfolio: '',
  careerObjective: '',
  additionalInfo: '',
  template: 'software-engineer',
  level: 'mid',
}

export const DEMO_PROFILES = [
  {
    id: 'software-engineer',
    name: 'Alex Morgan — Senior Full-Stack Engineer',
    icon: '💻',
    data: {
      fullName: 'Alex Morgan',
      username: 'alexmorgan.dev',
      email: 'alex.morgan@example.com',
      phone: '+1 (555) 234-5678',
      jobRole: 'Senior Full-Stack Engineer',
      company: 'TechCorp Solutions',
      skills: 'React, TypeScript, Node.js, Next.js, GraphQL, PostgreSQL, Docker, AWS, TailwindCSS, REST APIs',
      experience: '5+ years leading full-stack web applications. Architected cloud-native microservices reducing latency by 40%. Mentored junior engineers and spearheaded agile sprint cycles.',
      education: 'B.S. in Computer Science — University of California, Berkeley (2019)',
      projects: '1. DevFlow: Real-time collaborative workspace used by 15k+ developers.\n2. CloudSync: Automated DB backup utility with end-to-end encryption.',
      github: 'https://github.com/alexmorgan',
      linkedin: 'https://linkedin.com/in/alexmorgan-dev',
      portfolio: 'https://alexmorgan.io',
      careerObjective: 'To lead high-impact engineering teams building resilient, scalable, and delightful developer tools and AI-driven products.',
      additionalInfo: 'Open-source contributor to React & Vite ecosystem. Certified AWS Solutions Architect.',
      template: 'software-engineer',
      level: 'senior',
    },
  },
  {
    id: 'product-manager',
    name: 'Sarah Chen — Senior Product Manager',
    icon: '📊',
    data: {
      fullName: 'Sarah Chen',
      username: 'sarahchen_pm',
      email: 'sarah.chen@innovate.co',
      phone: '+1 (555) 876-5432',
      jobRole: 'Senior Product Manager',
      company: 'Innovate Labs',
      skills: 'Product Strategy, User Research, Agile/Scrum, A/B Testing, Roadmapping, Data Analytics, Jira, Figma, Cross-functional Leadership',
      experience: '4+ years driving product discovery and delivery for B2B SaaS platforms. Increased user retention by 28% and scaled ARR from $2M to $8M within 2 years.',
      education: 'B.A. in Economics & HCI — Stanford University (2020)',
      projects: '1. Onboarding 2.0: Revamped sign-up flow reducing drop-off by 35%.\n2. Analytics Hub: Built self-serve dashboard used by 500+ enterprise clients.',
      github: '',
      linkedin: 'https://linkedin.com/in/sarahchen-pm',
      portfolio: 'https://sarahchen.me',
      careerObjective: 'Passionate about building customer-centric software products that solve real problems through data-driven experimentation.',
      additionalInfo: 'Scrum Alliance Certified Product Owner (CSPO). Guest speaker at ProductCon 2025.',
      template: 'product-manager',
      level: 'senior',
    },
  },
  {
    id: 'ui-ux-designer',
    name: 'Liam Davies — Lead Product Designer',
    icon: '🎨',
    data: {
      fullName: 'Liam Davies',
      username: 'liamdesigns',
      email: 'liam@studioflow.design',
      phone: '+1 (555) 345-6789',
      jobRole: 'Lead UI/UX & Product Designer',
      company: 'Studio Flow',
      skills: 'UI/UX Design, Figma, Design Systems, Prototyping, Usability Testing, Wireframing, Micro-interactions, Motion Design, Accessibility (WCAG)',
      experience: '6 years crafting intuitive multi-platform mobile & web applications. Established enterprise design systems serving 12 product squads.',
      education: 'B.Des in Interaction Design — Rhode Island School of Design (2018)',
      projects: '1. Prism Design System: Component library with 200+ tokens and dark mode support.\n2. PayPulse App: Fintech wallet redesign rated 4.9 on App Store.',
      github: 'https://github.com/liamdesigns',
      linkedin: 'https://linkedin.com/in/liamdavies-design',
      portfolio: 'https://liamdavies.design',
      careerObjective: 'Creating seamless, elegant, and accessible user experiences that bridge user needs with business goals.',
      additionalInfo: 'Featured on Dribbble & Awwwards. Passionate about typography and design systems.',
      template: 'designer',
      level: 'senior',
    },
  },
]